CREATE TABLE charsheets (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  char_name TEXT NOT NULL,
  title TEXT NOT NULL,
  char_class TEXT NOT NULL,
  race TEXT NOT NULL,
  background TEXT NOT NULL,
  alignment TEXT NOT NULL,
  char_level NUMERIC NOT NULL,
  strength NUMERIC NOT NULL,
  dexterity NUMERIC NOT NULL,
  constitution NUMERIC NOT NULL,
  intelligence NUMERIC NOT NULL,
  wisdom NUMERIC NOT NULL,
  charisma NUMERIC NOT NULL
);
