CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  user_name TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  date_created TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE characters
  ADD COLUMN
    user_id INTEGER REFERENCES users(id)
    ON DELETE SET NULL;